syntax = "proto2";

package apollo.cyber.proto;

import "cyber/proto/qos_profile.proto";

// Socket 地址
message SocketAddr {
  optional string ip   = 1;  // IP地址, 点分十进制表示
  optional uint32 port = 2;  // 端口号
};

message RoleAttributes {
  optional string host_name       = 1;   // 主机名称
  optional string host_ip         = 2;   // 主机 IP 地址
  optional int32 process_id       = 3;   // 进程 ID
  optional string node_name       = 4;   // 节点名称
  optional uint64 node_id         = 5;   // 节点 ID

  // especially for WRITER and READER
  optional string channel_name    = 6;   // Channel 名称
  optional uint64 channel_id      = 7;   // Channel ID
  optional string message_type    = 8;   // Message 类型
  optional bytes proto_desc       = 9;   // Message 协议描述
  optional uint64 id              = 10;  // ID
  optional QosProfile qos_profile = 11;  // QoS Profile
  optional SocketAddr socket_addr = 12;  // Socket 地址

  // especially for SERVER and CLIENT
  optional string service_name    = 13;  // Service 名称
  optional uint64 service_id      = 14;  // Service ID
};
